//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usere
    {
        public int KodUser { get; set; }
        public string NameUser { get; set; }
        public string kodPermission { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    }
}
