//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int resourceCode { get; set; }
        public string resourceName { get; set; }
        public string filePath { get; set; }
        public string version { get; set; }
        public string authorName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> resourcePermission { get; set; }
    
        public virtual ResourcePermission ResourcePermission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
