//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userCode { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> permissionCode { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
